name: API Branch Build

on:
  pull_request:
    branches: [ main ]
    paths: 
      - 'src/backend/**'
  workflow_dispatch:  # Allow manual triggering

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_PATH: 'src/backend/Cta.Exercise.sln'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Configure NuGet with Artifactory
      run: |
        dotnet nuget add source ${{ variables.ARTIFACTORY_NUGET_URL }} \
          --name "Artifactory" \
          --username ${{ variables.ARTIFACTORY_USERNAME }} \
          --password ${{ secrets.ARTIFACTORY_PASSWORD }} \
          --store-password-in-clear-text
        
    - name: Restore NuGet packages
      run: dotnet restore ${{ env.SOLUTION_PATH }} --source "Artifactory" --source "${{ variables.ARTIFACTORY_NUGET_URL }}"
      
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
      
    - name: Test solution (if tests exist)
      run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-build --verbosity normal
      continue-on-error: true